// Table bake (Owner: UE-1): FRbTableContext for Preset -> RbTableMeshBuilder::BuildAll -> WriteStaticMesh per part to
// <RbAssetPaths::TableMeshDir>/<Preset>/SM_Table_<Part> (RbTableMeshBuilder::GetBakedMeshPackagePath) with the part's
// default material (RbAssetPaths, when it exists), Nanite with a 100 % fallback on every part but the thin sights
// (review R-02), complex-as-simple collision on every part (RbTableMeshBuilder::PartHasCollision). The same builder and options feed the
// runtime UDynamicMeshComponent path of ARbTable, so a baked part has exactly the runtime triangle count (checked here
// and by RawBreak.Unit.Table.BakedMatchesRuntime).

#include "RbAssetBakeLibrary.h"

#include "Core/RbAssetPaths.h"
#include "Simulation/RbTableContext.h"
#include "Table/RbTableMeshBuilder.h"

#include "Engine/StaticMesh.h"
#include "Materials/MaterialInterface.h"
#include "MeshDescription.h"
#include "Misc/PackageName.h"
#include "UObject/SoftObjectPath.h"

DEFINE_LOG_CATEGORY_STATIC(LogRbBakeTable, Log, All);

namespace
{
	UMaterialInterface* DefaultPartMaterial(ERbTablePart Part)
	{
		const TCHAR* Path = nullptr;
		switch (Part)
		{
		case ERbTablePart::Bed:
		case ERbTablePart::CushionCloth: Path = RbAssetPaths::MatCloth; break;
		case ERbTablePart::RailCaps:
		case ERbTablePart::Apron:
		case ERbTablePart::Legs: Path = RbAssetPaths::MatRailWood; break;
		case ERbTablePart::PocketLiners: Path = RbAssetPaths::MatPocketLiner; break;
		case ERbTablePart::Sights: Path = RbAssetPaths::MatSight; break;
		case ERbTablePart::Count: break;
		}
		if (!Path || !FPackageName::DoesPackageExist(Path))
		{
			return nullptr; // materials are generated by UE-3; ARbTable applies them at runtime once they exist
		}
		return Cast<UMaterialInterface>(FSoftObjectPath(Path).TryLoad());
	}
}

int32 URbAssetBakeLibrary::BakeTableMeshes(ERbTablePreset Preset, bool bNanite)
{
	FRbTableSetup Setup;
	Setup.Table = Preset;
	FString Error;
	const TSharedPtr<const FRbTableContext> Context = FRbTableContext::Create(Setup, Error);
	if (!Context.IsValid())
	{
		UE_LOG(LogRbBakeTable, Error, TEXT("BakeTableMeshes(%s): %s"), *RbTableMeshBuilder::GetPresetName(Preset), *Error);
		return -1;
	}
	FRbTableMeshSet Meshes;
	if (!RbTableMeshBuilder::BuildAll(Context->Geometry, FRbTableMeshOptions(), Meshes, Error))
	{
		UE_LOG(LogRbBakeTable, Error, TEXT("BakeTableMeshes(%s): %s"), *RbTableMeshBuilder::GetPresetName(Preset), *Error);
		return -1;
	}

	int32 Written = 0;
	for (int32 Index = 0; Index < static_cast<int32>(ERbTablePart::Count); ++Index)
	{
		const ERbTablePart Part = static_cast<ERbTablePart>(Index);
		const UE::Geometry::FDynamicMesh3& Mesh = Meshes.Get(Part);
		if (Mesh.TriangleCount() == 0)
		{
			continue; // e.g. legs disabled
		}
		const FString PackagePath = RbTableMeshBuilder::GetBakedMeshPackagePath(Preset, Part);
		UStaticMesh* StaticMesh = WriteStaticMesh(Mesh, PackagePath, DefaultPartMaterial(Part), bNanite && RbTableMeshBuilder::PartUsesNanite(Part),
			RbTableMeshBuilder::PartHasCollision(Part), Error);
		if (!StaticMesh)
		{
			UE_LOG(LogRbBakeTable, Error, TEXT("BakeTableMeshes: %s"), *Error);
			return -1;
		}
		// The asset must carry exactly the runtime mesh (source and built render data, full Nanite fallback).
		const FMeshDescription* Source = StaticMesh->GetMeshDescription(0);
		const int32 SourceTriangles = Source ? Source->Triangles().Num() : -1;
		const int32 RenderTriangles = StaticMesh->GetNumTriangles(0);
		if (SourceTriangles != Mesh.TriangleCount() || RenderTriangles != Mesh.TriangleCount())
		{
			UE_LOG(LogRbBakeTable, Error, TEXT("BakeTableMeshes: %s has %d source / %d render triangles, runtime mesh %d"), *PackagePath, SourceTriangles,
				RenderTriangles, Mesh.TriangleCount());
			return -1;
		}
		UE_LOG(LogRbBakeTable, Display, TEXT("baked %s: %d triangles, %d vertices, bounds %s"), *PackagePath, Mesh.TriangleCount(), Mesh.VertexCount(),
			*StaticMesh->GetBoundingBox().ToString());
		++Written;
	}
	return Written;
}
