#!/usr/bin/env python3
"""Decal preparation (venue-dive-bar 7, 13.1; Docs/ue-architecture.md 18.8): source art -> alpha, height, normal, roughness ->
4 x 4 atlases T_DB_DecalAtlas_<Set>_{BC,N,R}.png. Pure numpy + zlib (runs in the host Python and inside Blender, whose Python has
numpy but no Pillow), deterministic.

Two kinds of sources:
  * procedural cells (M2: rings, burns, scuffs, stains, chalk, water) generated by Tools/blender/divebar/db_decals.py with the
    helpers below (fbm noise, ring / blob / stroke primitives);
  * later (DB-5) Higgsfield decal art on a neutral grey or white background: `from_image()` keys the background out
    (alpha from the distance to the background colour), takes the height from the luminance and the roughness from the stain type.

Conventions: BC = sRGB colour + coverage in alpha (straight alpha); N = DirectX tangent-space normal (green down, Unreal's
convention) from the height by a Sobel filter; R = linear roughness in R, height in G, coverage in B (for roughness-only
"sticky" decals). Cell (i, j) of a 4 x 4 atlas = index j * 4 + i (row-major from the top left), the M_DB_Decal convention.

Host use (inspection):  python Tools/art/decal_prep.py --sheet Art/DiveBar/Textures/Decals  (writes a contact sheet with Pillow)
Owner: M2-B.
"""

from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path

import numpy as np

CELLS = 4


# --------------------------------------------------------------------------------------------------------------------
# PNG I/O (stdlib)
# --------------------------------------------------------------------------------------------------------------------


def write_png(path, pixels: np.ndarray) -> None:
	"""8-bit PNG from uint8 (H, W) / (H, W, 3) / (H, W, 4), rows top to bottom."""
	arr = np.ascontiguousarray(pixels)
	h, w = arr.shape[:2]
	channels = 1 if arr.ndim == 2 else arr.shape[2]
	color_type = {1: 0, 3: 2, 4: 6}[channels]
	raw = np.zeros((h, w * channels + 1), dtype=np.uint8)
	raw[:, 1:] = arr.reshape(h, w * channels)

	def chunk(tag: bytes, data: bytes) -> bytes:
		return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

	png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, color_type, 0, 0, 0))
	png += chunk(b"IDAT", zlib.compress(raw.tobytes(), 6)) + chunk(b"IEND", b"")
	path = Path(path)
	path.parent.mkdir(parents=True, exist_ok=True)
	path.write_bytes(png)


def to_u8(x: np.ndarray) -> np.ndarray:
	return (np.clip(x, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8)


def linear_to_srgb(c: np.ndarray) -> np.ndarray:
	c = np.clip(c, 0.0, 1.0)
	return np.where(c <= 0.0031308, 12.92 * c, 1.055 * np.power(c, 1.0 / 2.4) - 0.055)


# --------------------------------------------------------------------------------------------------------------------
# noise and primitives (float32 fields in [0, 1] on an n x n cell, coordinates -1..1)
# --------------------------------------------------------------------------------------------------------------------


def grid(n: int):
	c = (np.arange(n, dtype=np.float32) + 0.5) / n * 2.0 - 1.0
	x, y = np.meshgrid(c, c)
	return x, y


def _upsample(g: np.ndarray, n: int) -> np.ndarray:
	"""Bilinear upsampling of a small periodic grid to n x n (smooth value noise)."""
	m = g.shape[0]
	t = np.arange(n, dtype=np.float32) / n * m
	i0 = np.floor(t).astype(int) % m
	i1 = (i0 + 1) % m
	f = t - np.floor(t)
	f = f * f * (3.0 - 2.0 * f)
	rows = g[i0, :] * (1.0 - f)[:, None] + g[i1, :] * f[:, None]
	return rows[:, i0] * (1.0 - f)[None, :] + rows[:, i1] * f[None, :]


def fbm(n: int, rng: np.random.Generator, base: int = 4, octaves: int = 5, gain: float = 0.5) -> np.ndarray:
	out = np.zeros((n, n), dtype=np.float32)
	amp, total, size = 1.0, 0.0, base
	for _ in range(octaves):
		out += amp * _upsample(rng.random((size, size), dtype=np.float32), n)
		total += amp
		amp *= gain
		size *= 2
	return out / total


def smoothstep(a, b, x):
	t = np.clip((x - a) / (b - a), 0.0, 1.0)
	return t * t * (3.0 - 2.0 * t)


def polar(x, y, cx=0.0, cy=0.0):
	dx, dy = x - cx, y - cy
	return np.sqrt(dx * dx + dy * dy), np.arctan2(dy, dx)


# --------------------------------------------------------------------------------------------------------------------
# normal / packing
# --------------------------------------------------------------------------------------------------------------------


def normal_from_height(height: np.ndarray, strength: float) -> np.ndarray:
	"""Sobel -> DirectX normal, RGB 0..1. DirectX / Unreal: the tangent frame's +Y runs DOWN the image (rows top to bottom), so
	n = (-dh/dcol, -dh/drow, 1): a slope rising downwards (gy > 0) tilts the normal up the image -> green BELOW 0.5 (the ambientCG
	NormalDX / Poly Haven nor_dx maps follow it; the OpenGL sign made the decals' relief look lit from the wrong side)."""
	h = height.astype(np.float32)
	p = np.pad(h, 1, mode="edge")
	gx = (p[:-2, 2:] + 2 * p[1:-1, 2:] + p[2:, 2:]) - (p[:-2, :-2] + 2 * p[1:-1, :-2] + p[2:, :-2])
	gy = (p[2:, :-2] + 2 * p[2:, 1:-1] + p[2:, 2:]) - (p[:-2, :-2] + 2 * p[:-2, 1:-1] + p[:-2, 2:])
	nx = -gx * strength
	ny = -gy * strength
	nz = np.ones_like(h)
	inv = 1.0 / np.sqrt(nx * nx + ny * ny + nz * nz)
	return np.stack([nx * inv * 0.5 + 0.5, ny * inv * 0.5 + 0.5, nz * inv * 0.5 + 0.5], axis=-1)


def from_image(rgb: np.ndarray, background=(0.5, 0.5, 0.5), threshold: float = 0.08, roughness: float = 0.6):
	"""Higgsfield decal on a neutral background -> (colour, alpha, height, roughness) fields (0..1 floats). Alpha is the
	distance to the background colour; height is the luminance relative to the background."""
	bg = np.asarray(background, dtype=np.float32)
	d = np.sqrt(np.sum((rgb - bg) ** 2, axis=-1))
	alpha = smoothstep(threshold, threshold * 3.0, d)
	lum = rgb @ np.array([0.2126, 0.7152, 0.0722], dtype=np.float32)
	height = 0.5 + 0.5 * (lum - float(bg @ np.array([0.2126, 0.7152, 0.0722])))
	return rgb, alpha, height, np.full(alpha.shape, roughness, dtype=np.float32)


class Atlas:
	"""4 x 4 atlas of cells: put(index, colour (linear RGB), alpha, height, roughness)."""

	def __init__(self, cell_px: int = 512):
		self.cell = cell_px
		n = cell_px * CELLS
		self.color = np.zeros((n, n, 3), dtype=np.float32)
		self.alpha = np.zeros((n, n), dtype=np.float32)
		self.height = np.zeros((n, n), dtype=np.float32)
		self.rough = np.full((n, n), 0.5, dtype=np.float32)
		self.names: dict[int, str] = {}

	def put(self, index: int, name: str, color: np.ndarray, alpha: np.ndarray, height: np.ndarray, rough: np.ndarray) -> None:
		i, j = index % CELLS, index // CELLS
		c = self.cell
		sl = (slice(j * c, (j + 1) * c), slice(i * c, (i + 1) * c))
		# fade the border so bilinear / mip sampling never bleeds into the neighbour cell
		x, y = grid(c)
		edge = 1.0 - smoothstep(0.90, 0.99, np.maximum(np.abs(x), np.abs(y)))
		self.color[sl] = color
		self.alpha[sl] = alpha * edge
		self.height[sl] = height * edge
		self.rough[sl] = rough
		self.names[index] = name

	def write(self, folder, set_name: str, normal_strength: float = 6.0) -> dict:
		folder = Path(folder)
		bc = np.concatenate([linear_to_srgb(self.color), self.alpha[..., None]], axis=-1)
		write_png(folder / f"T_DB_DecalAtlas_{set_name}_BC.png", to_u8(bc))
		write_png(folder / f"T_DB_DecalAtlas_{set_name}_N.png", to_u8(normal_from_height(self.height, normal_strength)))
		r = np.stack([self.rough, self.height, self.alpha], axis=-1)
		write_png(folder / f"T_DB_DecalAtlas_{set_name}_R.png", to_u8(r))
		return {"cells": {str(k): v for k, v in sorted(self.names.items())}, "cell_px": self.cell, "grid": CELLS}


def main() -> int:
	import argparse

	p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	p.add_argument("--sheet", default="", help="folder with T_DB_DecalAtlas_*_BC.png: write a contact sheet (Pillow)")
	p.add_argument("--out", default="Saved/RbPreview/decal_sheet.png")
	a = p.parse_args()
	if a.sheet:
		from PIL import Image

		folder = Path(a.sheet)
		atlases = sorted(folder.glob("T_DB_DecalAtlas_*_BC.png"))
		tiles = []
		for path in atlases:
			im = Image.open(path).convert("RGBA")
			bg = Image.new("RGBA", im.size, (150, 140, 120, 255))
			tiles.append(Image.alpha_composite(bg, im).resize((512, 512)))
		sheet = Image.new("RGB", (512 * max(1, len(tiles)), 512))
		for k, t in enumerate(tiles):
			sheet.paste(t.convert("RGB"), (512 * k, 0))
		Path(a.out).parent.mkdir(parents=True, exist_ok=True)
		sheet.save(a.out)
		print(f"[decal_prep] {len(tiles)} atlases -> {a.out}")
	return 0


if __name__ == "__main__":
	sys.exit(main())
