#include "rb/Core/FpGuard.h"
// Owner: WP-3 (ball-ball & compliant islands). Spec: physics-collisions 3.6 (pressing), 3.9, 5.6 / 6.2 (rigid mode), 7.3;
// Docs/architecture.md 8.8 (sustained contacts, geometric contact order, tips, bounded features, exit hysteresis), 8.11
// (in-plane gravity inside islands).
#include "rb/Physics/Compliant.h"

#include "rb/Core/Assert.h"
#include "rb/Math/Scalar.h"

#include <algorithm>
#include <cstdint>
#include <new>

namespace rb
{
	namespace
	{
		// T_H = C (m*^2 / (K^2 v))^(1/5) with C = 2.9433 (5/4)^(2/5), 2.9433 = (4/5) B(2/5, 1/2) (collisions 3.9.3).
		constexpr double kHertzTimeConstant = 3.2180654597190435;

		// Verlet candidate list: pairs within skin + LeaveDistance are candidates; the list is rebuilt when a body has moved
		// more than half the skin since the last rebuild, so a pair outside the list can close by at most the skin and
		// stays more than LeaveDistance apart (no missed contact, correct re-arming).
		constexpr double kCandidateSkin = 2.0e-3; // [m]

		// Alpha_T(e) for the island integrator (semi-implicit Euler, dt = 1 us, 2 balls head-on at 1 m/s, K = 8.0587e8,
		// equal pool balls), at e = 0.50, 0.51, ..., 1.00. Generated by bisection with CompliantIsland itself (re-checked by
		// ARCH_CLI2 in Tests/Core/Compliant/TestCompliantArchitecture.cpp to 5e-5 at and between nodes); interpolated linearly
		// in -ln(e), in which alpha_T is nearly linear. alpha_T(0.95) = 0.036915 (spec 0.03689 / verifier 0.03692: the value
		// depends on the integrator in the 4th digit, 3.9.3).
		constexpr int kAlphaTableSize = 51;
		constexpr double kAlphaTableFirstE = 0.50;
		constexpr double kAlphaTableStep = 0.01;
		constexpr double kAlphaTable[kAlphaTableSize] = {
			0.57075368292311146, 0.55207121163375983, 0.53390557224102508, 0.51622842695796867, 0.49901734703501632,  // 0.50-0.54
			0.48225130527323712, 0.46591056866853187, 0.44997660116397786, 0.43443197536986844, 0.41926873198067294,  // 0.55-0.59
			0.40446543407787094, 0.39000519605451345, 0.37587423697006095, 0.36205955002322432, 0.34855713394554866,  // 0.60-0.64
			0.33535098286201315, 0.32242611037064128, 0.30977208948865298, 0.29738324903177926, 0.28525450579982836,  // 0.65-0.69
			0.2733682566077823, 0.26171607333605307, 0.25029464465747098, 0.23909959491674837, 0.22811541931681034,   // 0.70-0.74
			0.21733526488810512, 0.20676026946405834, 0.19638090609729114, 0.18618645361072117, 0.17617131969817762,  // 0.75-0.79
			0.16634142099917149, 0.15668006533457851, 0.14718218301963171, 0.13784692224805334, 0.12867251626767628,  // 0.80-0.84
			0.11964773958319672, 0.11076865445288184, 0.10203699408299499, 0.093446332885415428, 0.084989753474205704, // 0.85-0.89
			0.076664033659321784, 0.068469557521056101, 0.060402121845013479, 0.052455666806125054, 0.044627510919123758, // 0.90-0.94
			0.036915086040204201, 0.029315910919867592, 0.021827546058142272, 0.014447504039801027, 0.0071730289526758893, // 0.95-0.99
			0.0, // 1.00 (the undamped integrator gives e = 1 + 4e-7)
		};

		// Damping ratio of a linear spring-dashpot with restitution e (collisions 3.9.2): zeta = -ln(e) / sqrt(pi^2 + ln(e)^2).
		double DampingRatio(double Restitution)
		{
			if (!(Restitution > 0.0))
			{
				return 1.0;
			}
			if (!(Restitution < 1.0))
			{
				return 0.0;
			}
			const double L = -Log(Restitution);
			return L / Sqrt(kPi * kPi + L * L);
		}

		// Geometric sort key of the contact order: lexicographic (x, |y|, z), then y. Using |y| before the sign makes the order
		// of a body's contacts the mirror image of its mirror body's order for configurations symmetric about the long axis
		// y = 0 (the break), so per-body force sums are exactly mirror-symmetric there (COL CL-7); it is as id-independent as
		// plain (x, y, z) (CL-8).
		bool KeyLess(const Vec3& A, const Vec3& B)
		{
			if (A.x != B.x)
			{
				return A.x < B.x;
			}
			const double Ay = Abs(A.y);
			const double By = Abs(B.y);
			if (Ay != By)
			{
				return Ay < By;
			}
			if (A.z != B.z)
			{
				return A.z < B.z;
			}
			return A.y < B.y;
		}

		// Strict lexicographic (x, y, z) order (canonical pair roles).
		bool LexLess(const Vec3& A, const Vec3& B)
		{
			if (A.x != B.x)
			{
				return A.x < B.x;
			}
			if (A.y != B.y)
			{
				return A.y < B.y;
			}
			return A.z < B.z;
		}

		double InertiaK(const IslandBody& Body) { return Body.Inertia / (Body.Mass * Body.Radius * Body.Radius); }

		// Contact of a ball (centre P, radius R) with a bounded feature.
		struct FeatureHit
		{
			double Gap = kInfinity;  // signed gap [m] (< 0 = overlap)
			double Distance = 0.0;   // centre to the feature's contact curve / plane [m]
			Vec3 Normal;             // unit, from the feature toward the ball centre (the direction the ball is pushed)
			Vec3 Tangent;            // curve features: unit tangent of the edge at the contact point
			bool Curve = false;      // EdgeLine / JawCircle (a curve, not a surface)
		};

		bool InsidePolygon(const IslandFeature& F, double X, double Y)
		{
			if (F.VertexCount < 3)
			{
				return false;
			}
			for (int i = 0; i < F.VertexCount; ++i)
			{
				const Vec2& V0 = F.Vertices[i];
				const Vec2& V1 = F.Vertices[i + 1 < F.VertexCount ? i + 1 : 0];
				if (Cross(V1 - V0, Vec2{X - V0.x, Y - V0.y}) < 0.0)
				{
					return false;
				}
			}
			if (F.HasCut)
			{
				const double Dx = X - F.CutCenter.x;
				const double Dy = Y - F.CutCenter.y;
				if (Dx * Dx + Dy * Dy < F.CutRadius * F.CutRadius)
				{
					return false;
				}
			}
			return true;
		}

		// Exact contact geometry inside the feature's valid region (false = the feature cannot touch the ball there).
		bool FeatureContact(const IslandFeature& F, const Vec3& P, double R, FeatureHit& Hit)
		{
			switch (F.Kind)
			{
			case IslandFeatureKind::EdgeLine:
			{
				// Segment [Point, Point + Length Direction]; end caps are points; contact distance R + Radius.
				const double T = Clamp(Dot(P - F.Point, F.Direction), 0.0, F.Length);
				const Vec3 D = P - (F.Point + F.Direction * T);
				const double Dist = Length(D);
				Hit.Normal = Dist > 0.0 ? D * (1.0 / Dist) : F.Normal;
				Hit.Distance = Dist;
				Hit.Gap = Dist - (R + F.Radius);
				Hit.Tangent = F.Direction;
				Hit.Curve = true;
				return true;
			}
			case IslandFeatureKind::JawCircle:
			{
				// Horizontal circle of radius r_j at height h, exposed between AngleFrom and AngleFrom + AngleSweep.
				const double Hx = P.x - F.Point.x;
				const double Hy = P.y - F.Point.y;
				const double Rho = Sqrt(Hx * Hx + Hy * Hy);
				if (!(Rho > 0.0))
				{
					return false; // centre on the axis: every arc point is equidistant; the neighbouring features take it
				}
				double Rel = Atan2(Hy, Hx) - F.AngleFrom;
				Rel -= kTwoPi * Floor(Rel / kTwoPi);
				if (Rel > F.AngleSweep)
				{
					return false;
				}
				const Vec3 Radial{Hx / Rho, Hy / Rho, 0.0};
				const Vec3 D = P - (F.Point + Radial * F.Radius);
				const double Dist = Length(D);
				Hit.Normal = Dist > 0.0 ? D * (1.0 / Dist) : Radial;
				Hit.Distance = Dist;
				Hit.Gap = Dist - R;
				Hit.Tangent = Vec3{-Radial.y, Radial.x, 0.0};
				Hit.Curve = true;
				return true;
			}
			case IslandFeatureKind::FacingPlane:
			{
				const double Sigma = Dot(P - F.Point, F.Normal);
				if (!(Sigma > 0.0))
				{
					return false; // centre behind the face
				}
				const Vec3 Q = P - F.Normal * Sigma;
				const double T = Dot(Q - F.Point, F.Direction);
				if (T < 0.0 || T > F.Length || Q.z < F.ZMin || Q.z > F.ZMax)
				{
					return false;
				}
				Hit.Normal = F.Normal;
				Hit.Distance = Sigma;
				Hit.Gap = Sigma - R;
				Hit.Curve = false;
				return true;
			}
			case IslandFeatureKind::Plane:
			{
				const double Sigma = Dot(P - F.Point, F.Direction);
				if (!(Sigma > 0.0))
				{
					return false;
				}
				const Vec3 Q = P - F.Direction * Sigma;
				if (!InsidePolygon(F, Q.x, Q.y))
				{
					return false;
				}
				Hit.Normal = F.Direction;
				Hit.Distance = Sigma;
				Hit.Gap = Sigma - R;
				Hit.Curve = false;
				return true;
			}
			}
			return false;
		}

		// Conservative lower bound of the gap for the candidate list (valid region ignored or enlarged).
		double FeatureCandidateGap(const IslandFeature& F, const Vec3& P, double R, double Margin)
		{
			switch (F.Kind)
			{
			case IslandFeatureKind::EdgeLine:
			{
				const double T = Clamp(Dot(P - F.Point, F.Direction), 0.0, F.Length);
				return Length(P - (F.Point + F.Direction * T)) - (R + F.Radius);
			}
			case IslandFeatureKind::JawCircle:
			{
				const double Rho = Sqrt(Square(P.x - F.Point.x) + Square(P.y - F.Point.y));
				return Sqrt(Square(Rho - F.Radius) + Square(P.z - F.Point.z)) - R; // distance to the whole circle
			}
			case IslandFeatureKind::FacingPlane:
			{
				const Vec3 Rel = P - F.Point;
				const double Along = Dot(Rel, F.Direction);
				const double Reach = R + Margin;
				if (Along < -Reach || Along > F.Length + Reach || P.z < F.ZMin - Reach || P.z > F.ZMax + Reach)
				{
					return kInfinity;
				}
				return Abs(Dot(Rel, F.Normal)) - R;
			}
			case IslandFeatureKind::Plane:
			{
				if (F.VertexCount < 3)
				{
					return kInfinity;
				}
				double MinX = F.Vertices[0].x;
				double MaxX = MinX;
				double MinY = F.Vertices[0].y;
				double MaxY = MinY;
				for (int i = 1; i < F.VertexCount; ++i)
				{
					MinX = Min(MinX, F.Vertices[i].x);
					MaxX = Max(MaxX, F.Vertices[i].x);
					MinY = Min(MinY, F.Vertices[i].y);
					MaxY = Max(MaxY, F.Vertices[i].y);
				}
				const double Reach = R + Margin;
				if (P.x < MinX - Reach || P.x > MaxX + Reach || P.y < MinY - Reach || P.y > MaxY + Reach)
				{
					return kInfinity;
				}
				return Abs(Dot(P - F.Point, F.Direction)) - R;
			}
			}
			return kInfinity;
		}

		// A deterministic geometric point of the feature near the ball (the sort key of a ball-feature candidate).
		Vec3 FeatureKeyPoint(const IslandFeature& F, const Vec3& P)
		{
			switch (F.Kind)
			{
			case IslandFeatureKind::EdgeLine:
				return F.Point + F.Direction * Clamp(Dot(P - F.Point, F.Direction), 0.0, F.Length);
			case IslandFeatureKind::JawCircle:
			{
				const double Hx = P.x - F.Point.x;
				const double Hy = P.y - F.Point.y;
				const double Rho = Sqrt(Hx * Hx + Hy * Hy);
				const Vec3 Radial = Rho > 0.0 ? Vec3{Hx / Rho, Hy / Rho, 0.0} : Vec3{Cos(F.AngleFrom), Sin(F.AngleFrom), 0.0};
				return F.Point + Radial * F.Radius;
			}
			case IslandFeatureKind::FacingPlane:
				return P - F.Normal * Dot(P - F.Point, F.Normal);
			case IslandFeatureKind::Plane:
				return P - F.Direction * Dot(P - F.Point, F.Direction);
			}
			return P;
		}

		// Cloth support of one body for one compliant step (the step's contact forces and gravity are already in the
		// velocities; rigid mode solves the same law as a sequential-impulse contact). Returns true if the cloth carried the ball (then its centre is snapped to z = R).
		// Normal impulse = the one that cancels the downward velocity; Coulomb friction mu_s per impulse, capped at the
		// stop-slip impulse (exact rolling, exact rest); while rolling: rolling resistance mu_r and the rolling constraint
		// snap; always: spin deceleration alpha_sp about z (both scaled with the carried normal impulse).
		bool ApplyClothSupport(IslandBody& Body, double Dt, const ClothParams& Cloth, double Gravity, double EpsZ)
		{
			const double Height = Body.Position.z - Body.Radius;
			const bool Touching = Height <= EpsZ || Height + Body.Velocity.z * Dt < 0.0;
			if (!Touching || Body.Velocity.z > 0.0)
			{
				return false; // airborne or lifting off
			}
			const double NormalImpulse = -Body.Velocity.z * Body.Mass;
			Body.Velocity.z = 0.0;
			if (!(NormalImpulse > 0.0))
			{
				return true;
			}
			const double R = Body.Radius;
			const double K = InertiaK(Body);
			const double Ux = Body.Velocity.x - R * Body.Omega.y;
			const double Uy = Body.Velocity.y + R * Body.Omega.x;
			const double SlipSpeed = Sqrt(Ux * Ux + Uy * Uy);
			const double MaxImpulse = Cloth.SlidingFriction * NormalImpulse;
			const double StickFraction = K / (1.0 + K); // effective mass of the slip over m: 1 / (1 + m R^2 / I)
			if (SlipSpeed * Body.Mass * StickFraction <= MaxImpulse)
			{
				// Stick: the slip is removed exactly; the ball rolls. Rolling resistance (capped: exact rest), rolling snap.
				double Vx = Body.Velocity.x - Ux * StickFraction;
				double Vy = Body.Velocity.y - Uy * StickFraction;
				const double Speed = Sqrt(Vx * Vx + Vy * Vy);
				const double MaxDv = Cloth.RollingResistance * NormalImpulse / Body.Mass;
				if (Speed <= MaxDv)
				{
					Vx = 0.0;
					Vy = 0.0;
				}
				else
				{
					const double Scale = 1.0 - MaxDv / Speed;
					Vx *= Scale;
					Vy *= Scale;
				}
				Body.Velocity.x = Vx;
				Body.Velocity.y = Vy;
				Body.Omega.x = -Vy / R;
				Body.Omega.y = Vx / R;
			}
			else
			{
				// Slide: P = -mu_s J_N u_hat at the contact point -R z_hat: dv = P / m, dw = -R (z_hat x P) / I.
				const double Px = -MaxImpulse * Ux / SlipSpeed;
				const double Py = -MaxImpulse * Uy / SlipSpeed;
				Body.Velocity.x += Px / Body.Mass;
				Body.Velocity.y += Py / Body.Mass;
				Body.Omega.x += R * Py / Body.Inertia;
				Body.Omega.y -= R * Px / Body.Inertia;
			}
			if (Gravity > 0.0 && Body.Omega.z != 0.0)
			{
				const double MaxDw = Cloth.SpinDeceleration * NormalImpulse / (Body.Mass * Gravity);
				Body.Omega.z = Body.Omega.z > 0.0 ? Max(0.0, Body.Omega.z - MaxDw) : Min(0.0, Body.Omega.z + MaxDw);
			}
			return true;
		}

		// Rolling resistance and spin deceleration on a tilted support plane (rail top, rigid mode): the in-plane velocity is
		// reduced by mu_r J_N / m (capped), the rolling constraint w_t = (n x v_t) / R is restored, the spin about n decays.
		void ApplyPlaneRolling(IslandBody& Body, const Vec3& Normal, double NormalImpulse, double RollingResistance, double SpinDeceleration,
			double Gravity)
		{
			const double R = Body.Radius;
			const double Vn = Dot(Body.Velocity, Normal);
			Vec3 Vt = Body.Velocity - Normal * Vn;
			const double Speed = Length(Vt);
			const double MaxDv = RollingResistance * NormalImpulse / Body.Mass;
			Vt = Speed <= MaxDv ? Vec3{} : Vt * (1.0 - MaxDv / Speed);
			double Wn = Dot(Body.Omega, Normal);
			if (Gravity > 0.0)
			{
				const double MaxDw = SpinDeceleration * NormalImpulse / (Body.Mass * Gravity);
				Wn = Wn > 0.0 ? Max(0.0, Wn - MaxDw) : Min(0.0, Wn + MaxDw);
			}
			Body.Velocity = Vt + Normal * Vn;
			Body.Omega = Cross(Normal, Vt) / R + Normal * Wn;
		}

		// Post-exit acceleration of a body in event mode (for the pressing test of CanExit): sliding / rolling on the cloth
		// (with the tilt drive), otherwise ballistic.
		Vec3 FreeAcceleration(const IslandBody& Body, bool Supported, const ClothParams& Cloth, double Gravity, const Vec2& InPlane,
			const NumericsConfig& Numerics)
		{
			const bool OnCloth = Supported && Body.Position.z - Body.Radius <= Numerics.EpsZ && Abs(Body.Velocity.z) <= Numerics.EpsV;
			if (!OnCloth)
			{
				return Vec3{InPlane.x, InPlane.y, -Gravity};
			}
			const Vec3 U = SlipVelocity(Body.Velocity, Body.Omega, Body.Radius);
			const double SlipSpeed = Sqrt(U.x * U.x + U.y * U.y);
			if (SlipSpeed > Numerics.EpsV)
			{
				const double A = Cloth.SlidingFriction * Gravity / SlipSpeed;
				return Vec3{InPlane.x - A * U.x, InPlane.y - A * U.y, 0.0};
			}
			const double Speed = Sqrt(Body.Velocity.x * Body.Velocity.x + Body.Velocity.y * Body.Velocity.y);
			if (Speed > Numerics.EpsV)
			{
				const double K = InertiaK(Body);
				const double A = Cloth.RollingResistance * Gravity / Speed;
				return Vec3{InPlane.x / (1.0 + K) - A * Body.Velocity.x, InPlane.y / (1.0 + K) - A * Body.Velocity.y, 0.0};
			}
			return Vec3{}; // at rest: held by the static rolling resistance (validity rule)
		}

		// Rigid-mode contact (sequential impulses). Every lever arm of a sphere contact lies along the normal, so the
		// normal impulse produces no torque and the tangential effective mass is isotropic.
		struct RigidContact
		{
			std::int16_t Pair = -1;   // index into Pairs, or -1 (tip, cloth)
			std::int8_t A = -1;       // body index
			std::int8_t B = -1;       // second body index (ball-ball) or -1
			std::int8_t Tip = -1;     // strike index (tip contact) or -1
			bool Cloth = false;       // support contact of A with the cloth
			bool Plane = false;       // A rests on a Plane feature (rolling resistance after the sweeps)
			bool Sliding = true;      // friction at the Coulomb limit in the last sweep (no friction: sliding)
			std::int8_t Feature = -1; // feature index or -1
			Vec3 Normal;              // unit, pushes A away from the other element
			double LeverA = 0.0;      // contact point - centre of A = Normal * LeverA (< 0)
			double LeverB = 0.0;      // contact point - centre of B = Normal * LeverB (> 0)
			double NormalMass = 0.0;  // 1 / inverse effective mass along the normal
			double TangentMass = 0.0; // 1 / inverse effective mass in the tangent plane
			double Target = 0.0;      // separating normal velocity after the solve [m/s]
			double Mu = 0.0;
			double Approach = 0.0;    // approach speed at the step start [m/s]
			double ImpulseN = 0.0;    // accumulated normal impulse [N s]
			Vec3 ImpulseT;            // accumulated tangential impulse [N s]
		};

		// Pair contacts, one cloth contact per body, and up to 4 balls per cue tip (a 10 mm dome cannot touch more at once).
		constexpr int kMaxTipContactsPerStrike = 4;
		constexpr int kMaxRigidContacts = kMaxIslandContacts + kMaxBalls + kMaxStrikes * kMaxTipContactsPerStrike;
	}

	double HertzContactTime(double ApproachSpeed, double ReducedMass, double HertzStiffness)
	{
		// 3.9.3: 378 us at 0.5 m/s, 329 us at 1 m/s, 238 us at 5 m/s, 207 us at 10 m/s (pool balls).
		if (!(ApproachSpeed > 0.0) || !(HertzStiffness > 0.0) || !(ReducedMass > 0.0))
		{
			return kInfinity;
		}
		return kHertzTimeConstant * Pow(ReducedMass * ReducedMass / (HertzStiffness * HertzStiffness * ApproachSpeed), 0.2);
	}

	double TsujiDamping(double TsujiAlpha, double ReducedMass, double HertzStiffness)
	{
		return TsujiAlpha * Sqrt(ReducedMass * HertzStiffness);
	}

	double TsujiAlphaForRestitution(double Restitution)
	{
		// Out of the tabulated range: e >= 1 -> 0 (undamped), e < 0.5 -> alpha_T(0.5) (heavier damping is not a billiard
		// contact). Linear interpolation in u = -ln(e) between the table nodes.
		if (!(Restitution < 1.0))
		{
			return 0.0;
		}
		if (!(Restitution > kAlphaTableFirstE))
		{
			return kAlphaTable[0];
		}
		const double Position = (Restitution - kAlphaTableFirstE) / kAlphaTableStep;
		int Index = static_cast<int>(Floor(Position));
		if (Index > kAlphaTableSize - 2)
		{
			Index = kAlphaTableSize - 2;
		}
		const double E0 = kAlphaTableFirstE + kAlphaTableStep * Index;
		const double E1 = kAlphaTableFirstE + kAlphaTableStep * (Index + 1);
		const double U0 = -Log(E0);
		const double U1 = Index + 1 == kAlphaTableSize - 1 ? 0.0 : -Log(E1);
		const double U = -Log(Restitution);
		const double W = (U0 - U) / (U0 - U1);
		return kAlphaTable[Index] + (kAlphaTable[Index + 1] - kAlphaTable[Index]) * W;
	}

	double CueTipContactStiffness(double ContactTime, double BallMass, double CueMass)
	{
		// Half period pi sqrt(m_eff / k) = ContactTime of the linear tip contact (DERIVED).
		if (!(ContactTime > 0.0))
		{
			return 0.0;
		}
		const double EffectiveMass = BallMass * CueMass / (BallMass + CueMass);
		return kPi * kPi * EffectiveMass / (ContactTime * ContactTime);
	}

	double IslandJoinDistance(double ApproachSpeed, double ReducedMass, const CliParams& Params, double ContactTol)
	{
		// 3.9.2 step 1: delta_cl = max(eps_touch, 1.2 v_n T_H(v_n)): 0.40 mm at 1 m/s, 2.1 mm at 8 m/s.
		if (!(ApproachSpeed > 0.0))
		{
			return ContactTol;
		}
		const double Reach = Params.JoinFactor * ApproachSpeed * HertzContactTime(ApproachSpeed, ReducedMass, Params.HertzStiffness);
		return IsFinite(Reach) ? Max(ContactTol, Reach) : ContactTol;
	}

	void CompliantIsland::Reset(double StartTime, CliMode Mode, const CliParams& Params, const BallBallParams& BallBall, const ClothParams& Cloth,
		double Gravity, const NumericsConfig& Numerics)
	{
		CurrentTime = StartTime;
		CurrentMode = Mode;
		Settings = Params;
		if (Settings.TsujiAlpha < 0.0)
		{
			Settings.TsujiAlpha = TsujiAlphaForRestitution(BallBall.Restitution); // defensive: the simulator resolves it at Run start
		}
		ContactModel = BallBall;
		ClothSettings = Cloth;
		Tolerances = Numerics;
		GravityAccel = Gravity;
		InPlaneGravityAccel = Vec2{};
		Steps = 0;
		ZeroForceSteps = 0;
		PairsDirty = true;
		CandidateSkin = kCandidateSkin;
		Bodies.Clear();
		Features.Clear();
		Pairs.Clear();
		for (int i = 0; i < kMaxBalls; ++i)
		{
			ClothWarmNormal[i] = 0.0;
			ClothWarmTangent[i] = Vec3{};
		}
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			TipActive[s] = false;
			TipSpeed[s] = 0.0;
			TipCenter[s] = Vec3{};
			for (TipBallState& State : TipContacts[s])
			{
				State = TipBallState{};
			}
		}
	}

	bool CompliantIsland::AddBody(const IslandBody& NewBody)
	{
		RB_ASSERT(NewBody.Radius > 0.0 && NewBody.Mass > 0.0 && NewBody.Inertia > 0.0); // validated by Simulator::Run
		if (NewBody.Ball < 0 || NewBody.Ball >= kMaxBalls || FindBody(NewBody.Ball) >= 0)
		{
			return false;
		}
		if (!Bodies.PushBack(NewBody))
		{
			return false;
		}
		ClothWarmNormal[Bodies.Size() - 1] = 0.0;
		ClothWarmTangent[Bodies.Size() - 1] = Vec3{};
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			TipContacts[s][NewBody.Ball] = TipBallState{};
		}
		PairsDirty = true;
		return true;
	}

	bool CompliantIsland::AddFeature(const IslandFeature& NewFeature)
	{
		for (const IslandFeature& Existing : Features)
		{
			if (Existing.SourceKind == NewFeature.SourceKind && Existing.SourceIndex == NewFeature.SourceIndex && Existing.SourceSub == NewFeature.SourceSub)
			{
				return true;
			}
		}
		if (!Features.PushBack(NewFeature))
		{
			return false;
		}
		PairsDirty = true;
		return true;
	}

	bool CompliantIsland::RemoveBody(int Ball, IslandBody& Out)
	{
		const int Index = FindBody(Ball);
		if (Index < 0)
		{
			return false;
		}
		Out = Bodies[Index];
		Bodies.RemoveAt(Index);
		for (int i = Index; i < Bodies.Size(); ++i)
		{
			RebuildPosition[i] = RebuildPosition[i + 1];
			ClothWarmNormal[i] = ClothWarmNormal[i + 1];
			ClothWarmTangent[i] = ClothWarmTangent[i + 1];
		}
		// Drop every pair state of the body and renumber the others (the list order, i.e. the key order, is kept).
		int Write = 0;
		for (int i = 0; i < Pairs.Size(); ++i)
		{
			PairState P = Pairs[i];
			if (P.A == Index || P.B == Index)
			{
				continue;
			}
			if (P.A > Index)
			{
				--P.A;
			}
			if (P.B > Index)
			{
				--P.B;
			}
			Pairs[Write++] = P;
		}
		Pairs.Resize(Write);
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			TipContacts[s][Ball] = TipBallState{};
		}
		return true;
	}

	bool CompliantIsland::SetTip(int Strike, const IslandTip& Tip)
	{
		if (Strike < 0 || Strike >= kMaxStrikes)
		{
			return false;
		}
		Tips[Strike] = Tip;
		TipActive[Strike] = true;
		// Tip state at the island time from the uniformly decelerating path (StartTime = join time).
		const CueTipPath& Path = Tip.Path;
		const double Decel = Path.Deceleration;
		double Tau = Max(0.0, CurrentTime - Path.StartTime);
		if (Decel > 0.0)
		{
			Tau = Min(Tau, Max(0.0, Path.Speed0) / Decel);
		}
		TipSpeed[Strike] = Path.Speed0 - Decel * Tau;
		TipCenter[Strike] = Path.Start + Path.Direction * (Path.Speed0 * Tau - 0.5 * Decel * Tau * Tau);
		for (TipBallState& State : TipContacts[Strike])
		{
			State = TipBallState{};
		}
		return true;
	}

	bool CompliantIsland::RemoveTip(int Strike, CueTipPath& Out)
	{
		if (Strike < 0 || Strike >= kMaxStrikes || !TipActive[Strike])
		{
			return false;
		}
		// The tip's current state as a new analytic path at Time() (a tip pushed backwards leaves at rest).
		const CueTipPath& Path = Tips[Strike].Path;
		Out = Path;
		Out.Start = TipCenter[Strike];
		Out.Speed0 = Max(0.0, TipSpeed[Strike]);
		Out.StartTime = CurrentTime;
		if (Out.Speed0 > 0.0)
		{
			Out.StopTime = Path.Deceleration > 0.0 ? CurrentTime + Out.Speed0 / Path.Deceleration : kInfinity;
		}
		else
		{
			Out.StopTime = CurrentTime;
		}
		TipActive[Strike] = false;
		for (TipBallState& State : TipContacts[Strike])
		{
			State = TipBallState{};
		}
		return true;
	}

	bool CompliantIsland::HasTip(int Strike) const
	{
		return Strike >= 0 && Strike < kMaxStrikes && TipActive[Strike];
	}

	void CompliantIsland::SetInPlaneGravity(const Vec2& Accel)
	{
		InPlaneGravityAccel = Accel;
	}

	void CompliantIsland::SetMode(CliMode NewMode)
	{
		// Bodies, features and contact states (frozen friction coefficients, damping, arming) are kept; rigid warm starts restart.
		CurrentMode = NewMode;
		for (PairState& P : Pairs)
		{
			P.WarmNormal = 0.0;
			P.WarmTangent = Vec3{};
		}
		for (int i = 0; i < kMaxBalls; ++i)
		{
			ClothWarmNormal[i] = 0.0;
			ClothWarmTangent[i] = Vec3{};
		}
	}

	void CompliantIsland::RebuildPairs()
	{
		struct CandidateKey
		{
			Vec3 Point;
			Vec3 Normal;
			int SourceKind = -1; // -1 = ball-ball
			int SourceIndex = 0;
			int SourceSub = 0;
			int IdA = 0;
			int IdB = 0;
			int Feature = -1;
		};

		for (int Attempt = 0; Attempt < 2; ++Attempt)
		{
			CandidateSkin = Attempt == 0 ? kCandidateSkin : 0.0;
			const double Threshold = CandidateSkin + Tolerances.LeaveDistance;
			FixedVector<PairState, kMaxIslandContacts> NewPairs;
			CandidateKey Keys[kMaxIslandContacts];
			bool Overflow = false;

			auto CarryOver = [this](PairState& P)
			{
				for (const PairState& Old : Pairs)
				{
					const bool Same = P.B >= 0 ? (Old.B >= 0 && ((Old.A == P.A && Old.B == P.B) || (Old.A == P.B && Old.B == P.A)))
					                           : (Old.B < 0 && Old.A == P.A && Old.Feature == P.Feature);
					if (Same)
					{
						P.InContact = Old.InContact;
						P.Active = Old.Active;
						P.Armed = Old.Armed;
						P.SlowSteps = Old.SlowSteps;
						P.Mu0 = Old.Mu0;
						P.Restitution = Old.Restitution;
						P.WarmNormal = Old.WarmNormal;
						P.WarmTangent = Old.WarmTangent;
						if (P.B < 0)
						{
							P.Damping = Old.Damping;
						}
						return;
					}
				}
			};

			const int BodyCount = Bodies.Size();
			for (int i = 0; i < BodyCount && !Overflow; ++i)
			{
				for (int j = i + 1; j < BodyCount; ++j)
				{
					const IslandBody& Bi = Bodies[i];
					const IslandBody& Bj = Bodies[j];
					const double Dist = Length(Bj.Position - Bi.Position);
					const double Gap = Dist - (Bi.Radius + Bj.Radius);
					if (!(Gap <= Threshold))
					{
						continue;
					}
					if (NewPairs.IsFull())
					{
						Overflow = true;
						break;
					}
					const bool IFirst = LexLess(Bi.Position, Bj.Position) || (!LexLess(Bj.Position, Bi.Position) && Bi.Ball < Bj.Ball);
					const int A = IFirst ? i : j;
					const int B = IFirst ? j : i;
					const IslandBody& BodyA = Bodies[A];
					const IslandBody& BodyB = Bodies[B];
					PairState P;
					P.A = static_cast<std::int8_t>(A);
					P.B = static_cast<std::int8_t>(B);
					P.RadiusSum = BodyA.Radius + BodyB.Radius;
					P.Damping = TsujiDamping(Settings.TsujiAlpha, BodyA.Mass * BodyB.Mass / (BodyA.Mass + BodyB.Mass), Settings.HertzStiffness);
					CarryOver(P);
					CandidateKey& Key = Keys[NewPairs.Size()];
					Key = CandidateKey{};
					Key.Normal = Dist > 0.0 ? (BodyB.Position - BodyA.Position) / Dist : Vec3::UnitX();
					Key.Point = BodyA.Position + Key.Normal * (BodyA.Radius + 0.5 * Gap);
					Key.IdA = BodyA.Ball < BodyB.Ball ? BodyA.Ball : BodyB.Ball;
					Key.IdB = BodyA.Ball < BodyB.Ball ? BodyB.Ball : BodyA.Ball;
					NewPairs.PushBack(P);
				}
			}
			for (int i = 0; i < BodyCount && !Overflow; ++i)
			{
				const IslandBody& Body = Bodies[i];
				for (int f = 0; f < Features.Size(); ++f)
				{
					const IslandFeature& F = Features[f];
					if (!(FeatureCandidateGap(F, Body.Position, Body.Radius, Threshold) <= Threshold))
					{
						continue;
					}
					if (NewPairs.IsFull())
					{
						Overflow = true;
						break;
					}
					PairState P;
					P.A = static_cast<std::int8_t>(i);
					P.Feature = static_cast<std::int8_t>(f);
					CarryOver(P);
					CandidateKey& Key = Keys[NewPairs.Size()];
					Key = CandidateKey{};
					Key.Point = FeatureKeyPoint(F, Body.Position);
					Key.Normal = Normalized(Body.Position - Key.Point);
					Key.SourceKind = F.SourceKind;
					Key.SourceIndex = F.SourceIndex;
					Key.SourceSub = F.SourceSub;
					Key.IdA = Body.Ball;
					Key.Feature = f;
					NewPairs.PushBack(P);
				}
			}
			if (Overflow && Attempt == 0)
			{
				continue; // capacity fallback: only pairs within LeaveDistance (skin 0), rebuilt every step
			}

			// Id-independent geometric key order (contact point, canonical normal, feature source; ball ids only on exact ties).
			std::uint8_t Order[kMaxIslandContacts];
			const int Count = NewPairs.Size();
			for (int i = 0; i < Count; ++i)
			{
				Order[i] = static_cast<std::uint8_t>(i);
			}
			std::sort(Order, Order + Count, [&Keys](std::uint8_t L, std::uint8_t R)
			{
				const CandidateKey& KL = Keys[L];
				const CandidateKey& KR = Keys[R];
				if (KeyLess(KL.Point, KR.Point))
				{
					return true;
				}
				if (KeyLess(KR.Point, KL.Point))
				{
					return false;
				}
				if (KeyLess(KL.Normal, KR.Normal))
				{
					return true;
				}
				if (KeyLess(KR.Normal, KL.Normal))
				{
					return false;
				}
				if (KL.SourceKind != KR.SourceKind)
				{
					return KL.SourceKind < KR.SourceKind;
				}
				if (KL.SourceIndex != KR.SourceIndex)
				{
					return KL.SourceIndex < KR.SourceIndex;
				}
				if (KL.SourceSub != KR.SourceSub)
				{
					return KL.SourceSub < KR.SourceSub;
				}
				if (KL.IdA != KR.IdA)
				{
					return KL.IdA < KR.IdA;
				}
				if (KL.IdB != KR.IdB)
				{
					return KL.IdB < KR.IdB;
				}
				return KL.Feature < KR.Feature;
			});
			Pairs.Clear();
			for (int i = 0; i < Count; ++i)
			{
				Pairs.PushBack(NewPairs[Order[i]]);
			}
			break;
		}
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			RebuildPosition[i] = Bodies[i].Position;
		}
		PairsDirty = false;
	}

	void CompliantIsland::RebuildIfMoved()
	{
		const double Limit = 0.5 * CandidateSkin;
		const double LimitSquared = Limit * Limit;
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			if (!(LengthSquared(Bodies[i].Position - RebuildPosition[i]) <= LimitSquared) || CandidateSkin == 0.0)
			{
				RebuildPairs();
				return;
			}
		}
	}

	void CompliantIsland::Step(IslandRecordList& NewRecords)
	{
		if (PairsDirty)
		{
			RebuildPairs();
		}
		if (CurrentMode == CliMode::Rigid)
		{
			StepRigid(NewRecords);
		}
		else
		{
			StepCompliant(NewRecords);
		}
		++Steps;
		RebuildIfMoved();
	}

	void CompliantIsland::StepCompliant(IslandRecordList& NewRecords)
	{
		const double Dt = Settings.TimeStep;
		const double StepTime = CurrentTime;
		const double TouchBand = Tolerances.ContactTol;
		const double Leave = Tolerances.LeaveDistance;
		const double SlipReg = Settings.SlipRegularization;

		Vec3 Force[kMaxBalls];
		Vec3 Torque[kMaxBalls];
		bool AnyActive = false;

		// Pair contacts in key order (Jacobi: every force from the state at the start of the step).
		for (int PairIndex = 0; PairIndex < Pairs.Size(); ++PairIndex)
		{
			PairState& P = Pairs[PairIndex];
			const IslandBody& A = Bodies[P.A];
			if (P.B >= 0)
			{
				const IslandBody& B = Bodies[P.B];
				const Vec3 D = B.Position - A.Position;
				const double DistSquared = LengthSquared(D);
				const double RSum = P.RadiusSum;
				if (!(DistSquared < RSum * RSum) || !(DistSquared > 0.0))
				{
					P.InContact = false;
					P.Active = false;
					P.SlowSteps = 0;
					if (!P.Armed && DistSquared > Square(RSum + Leave))
					{
						P.Armed = true;
					}
					continue;
				}
				const double Dist = Sqrt(DistSquared);
				const Vec3 N = D * (1.0 / Dist); // A -> B
				const double Delta = RSum - Dist;
				const Vec3 LeverA = N * (A.Radius - 0.5 * Delta);
				const Vec3 LeverB = N * -(B.Radius - 0.5 * Delta);
				const Vec3 Rel = (A.Velocity + Cross(A.Omega, LeverA)) - (B.Velocity + Cross(B.Omega, LeverB));
				const double DeltaRate = Dot(Rel, N); // compression rate (> 0 approaching)
				const Vec3 Slip = Rel - N * DeltaRate;
				const double SlipSpeed = Length(Slip);
				if (!P.InContact)
				{
					P.InContact = true;
					P.Mu0 = BallBallFriction(SlipSpeed, ContactModel); // k_cling mu_b at first touch (k_venue, O-15)
					P.Restitution = ContactModel.Restitution;
				}
				const double SqrtDelta = Sqrt(Delta);
				double Fn = Settings.HertzStiffness * Delta * SqrtDelta + P.Damping * Sqrt(SqrtDelta) * DeltaRate;
				if (!(Fn > 0.0))
				{
					Fn = 0.0;
				}
				const bool Active = Fn > 0.0 && Delta > TouchBand;
				if (Active)
				{
					if (P.Armed) // first positive force since (re-)arming; a record that did not fit is retried
					{
						IslandContactRecord Record;
						Record.Kind = IslandRecordKind::BallBall;
						Record.Time = StepTime;
						const bool AFirst = A.Ball < B.Ball;
						Record.BallA = AFirst ? A.Ball : B.Ball;
						Record.BallB = AFirst ? B.Ball : A.Ball;
						Record.Normal = AFirst ? N : -N;
						Record.NormalSpeed = DeltaRate;
						if (NewRecords.PushBack(Record))
						{
							P.Armed = false;
						}
					}
					P.SlowSteps = Abs(DeltaRate) < Settings.SustainedSpeed ? P.SlowSteps + 1 : 0;
					AnyActive = true;
				}
				else
				{
					P.SlowSteps = 0;
				}
				P.Active = Active;
				if (Fn == 0.0)
				{
					continue;
				}
				Vec3 F = N * (-Fn); // on A
				if (P.Mu0 > 0.0 && SlipSpeed > 0.0)
				{
					F += Slip * (-P.Mu0 * Fn / Max(SlipSpeed, SlipReg));
				}
				Force[P.A] += F;
				Force[P.B] -= F;
				Torque[P.A] += Cross(LeverA, F);
				Torque[P.B] += Cross(LeverB, -F);
			}
			else
			{
				const IslandFeature& Fe = Features[P.Feature];
				FeatureHit Hit;
				const bool Valid = FeatureContact(Fe, A.Position, A.Radius, Hit);
				if (!Valid || !(Hit.Gap < 0.0))
				{
					P.InContact = false;
					P.Active = false;
					P.SlowSteps = 0;
					if (!P.Armed)
					{
						const double Gap = Valid ? Hit.Gap : FeatureCandidateGap(Fe, A.Position, A.Radius, 0.0);
						if (Gap > Tolerances.LeaveDistance)
						{
							P.Armed = true;
						}
					}
					continue;
				}
				const double Delta = -Hit.Gap;
				const Vec3 K = Hit.Normal; // feature -> ball
				const Vec3 Lever = K * -(A.Radius - Delta);
				const Vec3 Vc = A.Velocity + Cross(A.Omega, Lever);
				const double Vk = Dot(Vc, K);
				const double DeltaRate = -Vk;
				const Vec3 Slip = Vc - K * Vk;
				const double SlipSpeed = Length(Slip);
				if (!P.InContact)
				{
					P.InContact = true;
					P.Mu0 = Fe.Friction;
					const double E = Clamp(Fe.RestitutionScale * CushionRestitution(Max(DeltaRate, 0.0), Fe.Restitution), 0.0, 1.0);
					P.Restitution = E;
					P.Damping = 2.0 * DampingRatio(E) * Sqrt(A.Mass * Settings.CushionStiffness);
				}
				double Fn = Settings.CushionStiffness * Delta + P.Damping * DeltaRate;
				if (!(Fn > 0.0))
				{
					Fn = 0.0;
				}
				const bool Active = Fn > 0.0 && Delta > TouchBand;
				if (Active)
				{
					if (P.Armed) // first positive force since (re-)arming; a record that did not fit is retried
					{
						IslandContactRecord Record;
						Record.Kind = IslandRecordKind::BallFeature;
						Record.Time = StepTime;
						Record.BallA = A.Ball;
						Record.Feature = P.Feature;
						Record.Normal = K;
						Record.NormalSpeed = DeltaRate;
						if (NewRecords.PushBack(Record))
						{
							P.Armed = false;
						}
					}
					P.SlowSteps = Abs(DeltaRate) < Settings.SustainedSpeed ? P.SlowSteps + 1 : 0;
					AnyActive = true;
				}
				else
				{
					P.SlowSteps = 0;
				}
				P.Active = Active;
				if (Fn == 0.0)
				{
					continue;
				}
				Vec3 F = K * Fn;
				if (P.Mu0 > 0.0 && SlipSpeed > 0.0)
				{
					F += Slip * (-P.Mu0 * Fn / Max(SlipSpeed, SlipReg));
				}
				Force[P.A] += F;
				Torque[P.A] += Cross(Lever, F);
			}
		}

		// Cue tips (strike order): linear compliant contact with every body; the reaction along d on the tip is summed in
		// lexicographic order of the touched ball centres (id independence).
		double TipReaction[kMaxStrikes] = {};
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			const IslandTip& Tip = Tips[s];
			const Vec3 Dir = Tip.Path.Direction;
			const Vec3 TipVelocity = Dir * TipSpeed[s];
			struct Contribution
			{
				Vec3 Key;
				double Value;
				int Body;
				bool Begin;
				bool End;
				Vec3 Normal;
				double Rate;
			};
			Contribution Items[kMaxBalls];
			int ItemCount = 0;
			for (int i = 0; i < Bodies.Size(); ++i)
			{
				const IslandBody& Body = Bodies[i];
				TipBallState& State = TipContacts[s][Body.Ball];
				const Vec3 D = Body.Position - TipCenter[s];
				const double DistSquared = LengthSquared(D);
				const double RSum = Tip.Path.DomeRadius + Body.Radius;
				if (!(DistSquared < RSum * RSum) || !(DistSquared > 0.0))
				{
					if (State.Active)
					{
						Items[ItemCount++] = Contribution{Body.Position, 0.0, i, false, true, Vec3{}, 0.0};
					}
					State = TipBallState{};
					continue;
				}
				const double Dist = Sqrt(DistSquared);
				const Vec3 N = D * (1.0 / Dist); // tip -> ball
				const double Delta = RSum - Dist;
				const Vec3 Lever = N * -(Body.Radius - 0.5 * Delta);
				const Vec3 Rel = Body.Velocity + Cross(Body.Omega, Lever) - TipVelocity;
				const double Vn = Dot(Rel, N);
				const double DeltaRate = -Vn;
				const Vec3 Slip = Rel - N * Vn;
				const double SlipSpeed = Length(Slip);
				if (!State.InContact)
				{
					State.InContact = true;
					const double MassSum = Body.Mass + Tip.Mass;
					const double EffectiveMass = Tip.Mass > 0.0 ? Body.Mass * Tip.Mass / MassSum : Body.Mass;
					State.Damping = 2.0 * DampingRatio(Clamp(Tip.Restitution, 0.0, 1.0)) * Sqrt(EffectiveMass * Tip.Stiffness);
				}
				double Fn = Tip.Stiffness * Delta + State.Damping * DeltaRate;
				if (!(Fn > 0.0))
				{
					Fn = 0.0;
				}
				const bool Active = Fn > 0.0 && Delta > TouchBand;
				const bool Begin = Active && !State.Active;
				const bool End = !Active && State.Active;
				State.SlowSteps = Active && Abs(DeltaRate) < Settings.SustainedSpeed ? State.SlowSteps + 1 : 0;
				State.Active = Active;
				AnyActive = AnyActive || Active;
				double Along = 0.0;
				if (Fn > 0.0)
				{
					Vec3 F = N * Fn;
					if (Tip.Friction > 0.0 && SlipSpeed > 0.0)
					{
						F += Slip * (-Tip.Friction * Fn / Max(SlipSpeed, SlipReg));
					}
					Force[i] += F;
					Torque[i] += Cross(Lever, F);
					Along = -Dot(F, Dir);
				}
				if (Fn > 0.0 || Begin || End)
				{
					Items[ItemCount++] = Contribution{Body.Position, Along, i, Begin, End, N, DeltaRate};
				}
			}
			for (int i = 1; i < ItemCount; ++i)
			{
				for (int j = i; j > 0 && KeyLess(Items[j].Key, Items[j - 1].Key); --j)
				{
					const Contribution Swap = Items[j];
					Items[j] = Items[j - 1];
					Items[j - 1] = Swap;
				}
			}
			for (int i = 0; i < ItemCount; ++i)
			{
				TipReaction[s] += Items[i].Value;
				if (Items[i].Begin || Items[i].End)
				{
					IslandContactRecord Record;
					Record.Kind = Items[i].Begin ? IslandRecordKind::TipBegin : IslandRecordKind::TipEnd;
					Record.Time = StepTime;
					Record.BallA = Bodies[Items[i].Body].Ball;
					Record.Strike = s;
					Record.Normal = Items[i].Normal;
					Record.NormalSpeed = Items[i].Rate;
					NewRecords.PushBack(Record);
				}
			}
		}

		// Bodies: semi-implicit Euler (velocities, then positions), gravity (in-plane part only when non-zero), cloth.
		const bool Tilted = InPlaneGravityAccel.x != 0.0 || InPlaneGravityAccel.y != 0.0;
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			IslandBody& Body = Bodies[i];
			Vec3 Accel = Force[i] * (1.0 / Body.Mass);
			Accel.z -= GravityAccel;
			if (Tilted)
			{
				Accel.x += InPlaneGravityAccel.x;
				Accel.y += InPlaneGravityAccel.y;
			}
			Body.Velocity += Accel * Dt;
			Body.Omega += Torque[i] * (Dt / Body.Inertia);
			const bool Supported = Settings.ClothSupport && Body.ClothSupport && ApplyClothSupport(Body, Dt, ClothSettings, GravityAccel, Tolerances.EpsZ);
			Body.Position += Body.Velocity * Dt;
			if (Supported)
			{
				Body.Position.z = Body.Radius;
			}
		}

		// Tips: the contact reaction, then the prescribed deceleration toward rest (the hand), then the position.
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			const IslandTip& Tip = Tips[s];
			double V = TipSpeed[s];
			if (Tip.Mass > 0.0)
			{
				V += TipReaction[s] * (Dt / Tip.Mass);
			}
			const double Dv = Tip.Path.Deceleration * Dt;
			V = V > 0.0 ? Max(0.0, V - Dv) : Min(0.0, V + Dv);
			TipSpeed[s] = V;
			TipCenter[s] += Tip.Path.Direction * (V * Dt);
		}

		ZeroForceSteps = AnyActive ? 0 : ZeroForceSteps + 1;
		CurrentTime = StepTime + Dt;
	}

	void CompliantIsland::StepRigid(IslandRecordList& NewRecords)
	{
		const double Dt = Settings.RigidTimeStep;
		const double StepTime = CurrentTime;
		const double RestSpeed = Tolerances.RestSpeed;

		// 1. External forces: gravity (the in-plane part only when non-zero). Inverse masses and inertias once per step.
		double InvMass[kMaxBalls];
		double InvInertia[kMaxBalls];
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			InvMass[i] = 1.0 / Bodies[i].Mass;
			InvInertia[i] = 1.0 / Bodies[i].Inertia;
		}
		const bool Tilted = InPlaneGravityAccel.x != 0.0 || InPlaneGravityAccel.y != 0.0;
		for (IslandBody& Body : Bodies)
		{
			Body.Velocity.z -= GravityAccel * Dt;
			if (Tilted)
			{
				Body.Velocity.x += InPlaneGravityAccel.x * Dt;
				Body.Velocity.y += InPlaneGravityAccel.y * Dt;
			}
		}

		// 2. Contacts: pairs in key order (touching, or closing their gap within this step), tips, cloth.
		// Uninitialised storage: only the used entries are constructed (a value-initialised array would clear ~27 KB per step).
		alignas(RigidContact) unsigned char ContactStorage[sizeof(RigidContact) * kMaxRigidContacts];
		RigidContact* const Contacts = reinterpret_cast<RigidContact*>(ContactStorage);
		int ContactCount = 0;
		auto Push = [&](const RigidContact& C) { new (&Contacts[ContactCount++]) RigidContact(C); };
		auto ContactVelocity = [this](const RigidContact& C, Vec3& Relative)
		{
			const IslandBody& A = Bodies[C.A];
			Relative = A.Velocity + Cross(A.Omega, C.Normal * C.LeverA);
			if (C.B >= 0)
			{
				const IslandBody& B = Bodies[C.B];
				Relative -= B.Velocity + Cross(B.Omega, C.Normal * C.LeverB);
			}
			else if (C.Tip >= 0)
			{
				Relative -= Tips[C.Tip].Path.Direction * TipSpeed[C.Tip];
			}
		};
		auto Finish = [&](RigidContact& C, double Gap, double Restitution)
		{
			Vec3 Relative;
			ContactVelocity(C, Relative);
			C.Approach = -Dot(Relative, C.Normal);
			const double E = C.Approach > RestSpeed ? Restitution : 0.0;
			C.Target = Gap > 0.0 && E == 0.0 ? -Gap / Dt : E * C.Approach;
		};
		auto WillTouch = [&](const RigidContact& C, double Gap)
		{
			if (!(Gap > 0.0))
			{
				return true;
			}
			Vec3 Relative;
			ContactVelocity(C, Relative);
			return -Dot(Relative, C.Normal) * Dt > Gap;
		};

		for (int PairIndex = 0; PairIndex < Pairs.Size(); ++PairIndex)
		{
			PairState& P = Pairs[PairIndex];
			const IslandBody& A = Bodies[P.A];
			RigidContact C;
			C.Pair = static_cast<std::int16_t>(PairIndex);
			C.A = P.A;
			double Gap = 0.0;
			if (P.B >= 0)
			{
				const IslandBody& B = Bodies[P.B];
				const Vec3 D = A.Position - B.Position;
				const double Dist = Length(D);
				if (!(Dist > 0.0))
				{
					continue;
				}
				Gap = Dist - P.RadiusSum;
				C.B = P.B;
				C.Normal = D * (1.0 / Dist); // pushes A away from B
				const double Overlap = Max(0.0, -Gap);
				C.LeverA = -(A.Radius - 0.5 * Overlap);
				C.LeverB = B.Radius - 0.5 * Overlap;
				if (!WillTouch(C, Gap))
				{
					continue;
				}
				C.NormalMass = 1.0 / (InvMass[P.A] + InvMass[P.B]);
				C.TangentMass = 1.0 / (InvMass[P.A] + C.LeverA * C.LeverA * InvInertia[P.A] + InvMass[P.B] + C.LeverB * C.LeverB * InvInertia[P.B]);
				if (!P.InContact)
				{
					Vec3 Relative;
					ContactVelocity(C, Relative);
					const Vec3 Slip = Relative - C.Normal * Dot(Relative, C.Normal);
					P.Mu0 = BallBallFriction(Length(Slip), ContactModel);
					P.Restitution = ContactModel.Restitution;
				}
			}
			else
			{
				const IslandFeature& Fe = Features[P.Feature];
				FeatureHit Hit;
				if (!FeatureContact(Fe, A.Position, A.Radius, Hit))
				{
					continue;
				}
				Gap = Hit.Gap;
				C.Feature = P.Feature;
				C.Plane = Fe.Kind == IslandFeatureKind::Plane;
				C.Normal = Hit.Normal;
				C.LeverA = -(A.Radius - Max(0.0, -Gap));
				if (!WillTouch(C, Gap))
				{
					continue;
				}
				C.NormalMass = A.Mass;
				C.TangentMass = 1.0 / (InvMass[P.A] + C.LeverA * C.LeverA * InvInertia[P.A]);
				if (!P.InContact)
				{
					Vec3 Relative;
					ContactVelocity(C, Relative);
					P.Mu0 = Fe.Friction;
					P.Restitution = Clamp(Fe.RestitutionScale * CushionRestitution(Max(0.0, -Dot(Relative, C.Normal)), Fe.Restitution), 0.0, 1.0);
				}
			}
			C.Mu = P.Mu0;
			Finish(C, Gap, P.Restitution);
			Push(C);
		}
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			const IslandTip& Tip = Tips[s];
			const Vec3 Dir = Tip.Path.Direction;
			int TipContactCount = 0;
			for (int i = 0; i < Bodies.Size() && TipContactCount < kMaxTipContactsPerStrike; ++i)
			{
				const IslandBody& Body = Bodies[i];
				const Vec3 D = Body.Position - TipCenter[s];
				const double Dist = Length(D);
				if (!(Dist > 0.0))
				{
					continue;
				}
				const double Gap = Dist - (Tip.Path.DomeRadius + Body.Radius);
				RigidContact C;
				C.A = static_cast<std::int8_t>(i);
				C.Tip = static_cast<std::int8_t>(s);
				C.Normal = D * (1.0 / Dist);
				C.LeverA = -(Body.Radius - 0.5 * Max(0.0, -Gap));
				if (!WillTouch(C, Gap))
				{
					continue;
				}
				const double Along = Dot(Dir, C.Normal);
				const double TipInverse = Tip.Mass > 0.0 ? Along * Along / Tip.Mass : 0.0;
				C.NormalMass = 1.0 / (InvMass[i] + TipInverse);
				C.TangentMass = 1.0 / (InvMass[i] + C.LeverA * C.LeverA * InvInertia[i]); // the hand absorbs tangential forces
				C.Mu = Tip.Friction;
				Finish(C, Gap, Clamp(Tip.Restitution, 0.0, 1.0));
				// Sweep order of one tip's contacts: by the ball centres' key (id independence).
				int Slot = ContactCount - TipContactCount;
				while (Slot < ContactCount && KeyLess(Bodies[Contacts[Slot].A].Position, Body.Position))
				{
					++Slot;
				}
				Push(C);
				for (int k = ContactCount - 1; k > Slot; --k)
				{
					const RigidContact Swap = Contacts[k];
					Contacts[k] = Contacts[k - 1];
					Contacts[k - 1] = Swap;
				}
				++TipContactCount;
			}
		}
		if (Settings.ClothSupport)
		{
			for (int i = 0; i < Bodies.Size(); ++i)
			{
				const IslandBody& Body = Bodies[i];
				if (!Body.ClothSupport)
				{
					continue;
				}
				const double Gap = Body.Position.z - Body.Radius;
				const bool Touching = Gap <= Tolerances.EpsZ || Gap + Body.Velocity.z * Dt < 0.0;
				if (!Touching)
				{
					continue;
				}
				RigidContact C;
				C.A = static_cast<std::int8_t>(i);
				C.Cloth = true;
				C.Normal = Vec3::UnitZ();
				C.LeverA = -Body.Radius;
				C.NormalMass = Body.Mass;
				C.TangentMass = 1.0 / (InvMass[i] + Body.Radius * Body.Radius * InvInertia[i]);
				C.Mu = ClothSettings.SlidingFriction;
				C.Approach = -Body.Velocity.z;
				C.Target = Gap > 0.0 ? -Gap / Dt : 0.0; // landings inside islands are inelastic
				Push(C);
			}
		}

		// 3. Sequential impulses (Gauss-Seidel in the order above), Coulomb friction with the accumulated normal impulse.
		// Every lever arm lies along the normal: a normal impulse changes only the velocities, a tangential impulse P adds the
		// angular change (lever n x P) / I.
		auto ApplyNormal = [&](const RigidContact& C, const Vec3& Impulse)
		{
			Bodies[C.A].Velocity += Impulse * InvMass[C.A];
			if (C.B >= 0)
			{
				Bodies[C.B].Velocity -= Impulse * InvMass[C.B];
			}
		};
		auto ApplyTangent = [&](const RigidContact& C, const Vec3& Impulse)
		{
			const Vec3 Moment = Cross(C.Normal, Impulse);
			IslandBody& A = Bodies[C.A];
			A.Velocity += Impulse * InvMass[C.A];
			A.Omega += Moment * (C.LeverA * InvInertia[C.A]);
			if (C.B >= 0)
			{
				IslandBody& B = Bodies[C.B];
				B.Velocity -= Impulse * InvMass[C.B];
				B.Omega -= Moment * (C.LeverB * InvInertia[C.B]);
			}
		};
		// Warm start of sustained contacts (no bounce this step): the last step's impulses, the tangential one projected onto
		// the current tangent plane and clamped to the friction cone. Then a sweep that changes no contact velocity by more than
		// EpsV ends the solve early (deterministic: a function of the state only).
		for (int c = 0; c < ContactCount; ++c)
		{
			RigidContact& C = Contacts[c];
			if (C.Target > 0.0 || C.Tip >= 0)
			{
				continue;
			}
			const double WarmN = C.Cloth ? ClothWarmNormal[C.A] : Pairs[C.Pair].WarmNormal;
			if (!(WarmN > 0.0))
			{
				continue;
			}
			Vec3 WarmT = C.Cloth ? ClothWarmTangent[C.A] : Pairs[C.Pair].WarmTangent;
			WarmT -= C.Normal * Dot(WarmT, C.Normal);
			const double Limit = C.Mu * WarmN;
			const double Magnitude = Length(WarmT);
			if (Magnitude > Limit)
			{
				WarmT = Magnitude > 0.0 ? WarmT * (Limit / Magnitude) : Vec3{};
			}
			C.ImpulseN = WarmN;
			C.ImpulseT = WarmT;
			ApplyNormal(C, C.Normal * WarmN);
			ApplyTangent(C, WarmT);
		}
		const double ConvergedSpeed = Tolerances.EpsV;
		for (int Iteration = 0; Iteration < Settings.RigidIterations; ++Iteration)
		{
			double LargestChange = 0.0;
			for (int c = 0; c < ContactCount; ++c)
			{
				RigidContact& C = Contacts[c];
				Vec3 Relative;
				ContactVelocity(C, Relative);
				const double Separation = Dot(Relative, C.Normal);
				const double NewImpulse = Max(0.0, C.ImpulseN + (C.Target - Separation) * C.NormalMass);
				const double Delta = NewImpulse - C.ImpulseN;
				C.ImpulseN = NewImpulse;
				LargestChange = Max(LargestChange, Abs(Delta) / C.NormalMass);
				if (Delta != 0.0)
				{
					const Vec3 Impulse = C.Normal * Delta;
					ApplyNormal(C, Impulse);
					if (C.Tip >= 0 && Tips[C.Tip].Mass > 0.0)
					{
						TipSpeed[C.Tip] -= Dot(Impulse, Tips[C.Tip].Path.Direction) / Tips[C.Tip].Mass;
					}
				}
				if (!(C.Mu > 0.0))
				{
					continue;
				}
				ContactVelocity(C, Relative);
				const Vec3 Tangential = Relative - C.Normal * Dot(Relative, C.Normal);
				Vec3 NewT = C.ImpulseT - Tangential * C.TangentMass;
				const double Limit = C.Mu * C.ImpulseN;
				const double Magnitude = Length(NewT);
				C.Sliding = Magnitude > Limit;
				if (C.Sliding)
				{
					NewT = Magnitude > 0.0 ? NewT * (Limit / Magnitude) : Vec3{};
				}
				const Vec3 DeltaT = NewT - C.ImpulseT;
				C.ImpulseT = NewT;
				LargestChange = Max(LargestChange, Length(DeltaT) / C.TangentMass);
				ApplyTangent(C, DeltaT);
			}
			if (LargestChange <= ConvergedSpeed)
			{
				break;
			}
		}

		// 4. Supports: rolling resistance and spin deceleration while rolling (friction below the Coulomb limit).
		for (int c = 0; c < ContactCount; ++c)
		{
			const RigidContact& C = Contacts[c];
			if (!(C.ImpulseN > 0.0) || (!C.Cloth && !C.Plane))
			{
				continue;
			}
			IslandBody& Body = Bodies[C.A];
			const bool Rolling = !C.Sliding;
			if (C.Cloth)
			{
				if (Abs(Body.Velocity.z) <= Tolerances.EpsV)
				{
					Body.Velocity.z = 0.0; // carried by the cloth: no rounding residue of the normal solve (exact rest, A-CLI-5)
				}
				if (Rolling)
				{
					const double MaxDv = ClothSettings.RollingResistance * C.ImpulseN * InvMass[C.A];
					double Vx = Body.Velocity.x;
					double Vy = Body.Velocity.y;
					const double Speed = Sqrt(Vx * Vx + Vy * Vy);
					if (Speed <= MaxDv)
					{
						Vx = 0.0;
						Vy = 0.0;
					}
					else
					{
						const double Scale = 1.0 - MaxDv / Speed;
						Vx *= Scale;
						Vy *= Scale;
					}
					Body.Velocity.x = Vx;
					Body.Velocity.y = Vy;
					Body.Omega.x = -Vy / Body.Radius;
					Body.Omega.y = Vx / Body.Radius;
				}
				if (GravityAccel > 0.0 && Body.Omega.z != 0.0)
				{
					const double MaxDw = ClothSettings.SpinDeceleration * C.ImpulseN / (Body.Mass * GravityAccel);
					Body.Omega.z = Body.Omega.z > 0.0 ? Max(0.0, Body.Omega.z - MaxDw) : Min(0.0, Body.Omega.z + MaxDw);
				}
			}
			else if (Rolling)
			{
				const IslandFeature& Fe = Features[C.Feature];
				ApplyPlaneRolling(Body, C.Normal, C.ImpulseN, Fe.RollingResistance, Fe.SpinDeceleration, GravityAccel);
			}
		}

		// 5. Positions; tips (deceleration toward rest, then the position).
		for (IslandBody& Body : Bodies)
		{
			Body.Position += Body.Velocity * Dt;
		}
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			const double Dv = Tips[s].Path.Deceleration * Dt;
			double V = TipSpeed[s];
			V = V > 0.0 ? Max(0.0, V - Dv) : Min(0.0, V + Dv);
			TipSpeed[s] = V;
			TipCenter[s] += Tips[s].Path.Direction * (V * Dt);
		}

		// 6. Position projection (non-linear Gauss-Seidel, same order): overlaps are removed without changing velocities.
		for (int Iteration = 0; Iteration < Settings.RigidIterations; ++Iteration)
		{
			bool Corrected = false;
			for (int c = 0; c < ContactCount; ++c)
			{
				const RigidContact& C = Contacts[c];
				IslandBody& A = Bodies[C.A];
				if (C.Cloth)
				{
					continue;
				}
				if (C.B >= 0)
				{
					IslandBody& B = Bodies[C.B];
					const Vec3 D = A.Position - B.Position;
					const double Dist = Length(D);
					const double Gap = Dist - Pairs[C.Pair].RadiusSum;
					if (Gap < 0.0 && Dist > 0.0)
					{
						const Vec3 N = D * (1.0 / Dist);
						const double InvA = InvMass[C.A];
						const double InvB = InvMass[C.B];
						const double Share = -Gap / (InvA + InvB);
						A.Position += N * (Share * InvA);
						B.Position -= N * (Share * InvB);
						Corrected = true;
					}
				}
				else if (C.Tip >= 0)
				{
					const Vec3 D = A.Position - TipCenter[C.Tip];
					const double Dist = Length(D);
					const double Gap = Dist - (Tips[C.Tip].Path.DomeRadius + A.Radius);
					if (Gap < 0.0 && Dist > 0.0)
					{
						A.Position += D * (-Gap / Dist);
						Corrected = true;
					}
				}
				else
				{
					FeatureHit Hit;
					if (FeatureContact(Features[C.Feature], A.Position, A.Radius, Hit) && Hit.Gap < 0.0)
					{
						A.Position += Hit.Normal * (-Hit.Gap);
						Corrected = true;
					}
				}
			}
			if (Settings.ClothSupport)
			{
				for (IslandBody& Body : Bodies)
				{
					if (Body.ClothSupport && Body.Position.z < Body.Radius)
					{
						Body.Position.z = Body.Radius;
						Corrected = true;
					}
				}
			}
			if (!Corrected)
			{
				break; // nothing overlapped: further sweeps would not move anything
			}
		}

		// 7. Contact states and records (key order), tip records, warm starts of the next step.
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			ClothWarmNormal[i] = 0.0;
			ClothWarmTangent[i] = Vec3{};
		}
		for (int c = 0; c < ContactCount; ++c)
		{
			if (Contacts[c].Cloth)
			{
				ClothWarmNormal[Contacts[c].A] = Contacts[c].ImpulseN;
				ClothWarmTangent[Contacts[c].A] = Contacts[c].ImpulseT;
			}
		}
		bool AnyActive = false;
		int Cursor = 0;
		for (int PairIndex = 0; PairIndex < Pairs.Size(); ++PairIndex)
		{
			PairState& P = Pairs[PairIndex];
			const RigidContact* C = nullptr;
			if (Cursor < ContactCount && Contacts[Cursor].Pair == PairIndex)
			{
				C = &Contacts[Cursor++];
			}
			const bool Active = C != nullptr && C->ImpulseN / C->NormalMass > Tolerances.ApproachSpeedTol;
			P.SlowSteps = 0;
			P.WarmNormal = C != nullptr ? C->ImpulseN : 0.0;
			P.WarmTangent = C != nullptr ? C->ImpulseT : Vec3{};
			if (Active)
			{
				AnyActive = true;
				P.InContact = true;
				if (P.Armed) // first positive force since (re-)arming; a record that did not fit is retried
				{
					IslandContactRecord Record;
					Record.Time = StepTime;
					Record.NormalSpeed = C->Approach;
					if (P.B >= 0)
					{
						const int IdA = Bodies[P.A].Ball;
						const int IdB = Bodies[P.B].Ball;
						Record.Kind = IslandRecordKind::BallBall;
						Record.BallA = IdA < IdB ? IdA : IdB;
						Record.BallB = IdA < IdB ? IdB : IdA;
						Record.Normal = IdA < IdB ? -C->Normal : C->Normal; // from the lower id to the higher
					}
					else
					{
						Record.Kind = IslandRecordKind::BallFeature;
						Record.BallA = Bodies[P.A].Ball;
						Record.Feature = P.Feature;
						Record.Normal = C->Normal;
					}
					if (NewRecords.PushBack(Record))
					{
						P.Armed = false;
					}
				}
				P.Active = true;
				continue;
			}
			P.Active = false;
			// Geometric contact state and re-arming from the gap after the step.
			const IslandBody& A = Bodies[P.A];
			double Gap = kInfinity;
			if (P.B >= 0)
			{
				Gap = Length(Bodies[P.B].Position - A.Position) - P.RadiusSum;
			}
			else
			{
				FeatureHit Hit;
				Gap = FeatureContact(Features[P.Feature], A.Position, A.Radius, Hit) ? Hit.Gap
				                                                                      : FeatureCandidateGap(Features[P.Feature], A.Position, A.Radius, 0.0);
			}
			P.InContact = Gap <= Tolerances.ContactTol;
			if (!P.Armed && Gap > Tolerances.LeaveDistance)
			{
				P.Armed = true;
			}
		}
		for (int c = Cursor; c < ContactCount; ++c)
		{
			const RigidContact& C = Contacts[c];
			if (C.Tip < 0)
			{
				continue;
			}
			const bool Active = C.ImpulseN / C.NormalMass > Tolerances.ApproachSpeedTol;
			AnyActive = AnyActive || Active;
			TipBallState& State = TipContacts[C.Tip][Bodies[C.A].Ball];
			if (Active != State.Active)
			{
				IslandContactRecord Record;
				Record.Kind = Active ? IslandRecordKind::TipBegin : IslandRecordKind::TipEnd;
				Record.Time = StepTime;
				Record.BallA = Bodies[C.A].Ball;
				Record.Strike = C.Tip;
				Record.Normal = C.Normal;
				Record.NormalSpeed = C.Approach;
				NewRecords.PushBack(Record);
			}
			State.Active = Active;
			State.InContact = true;
		}
		// Tip contacts that were active but are no longer in the contact set end now.
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			for (int i = 0; i < Bodies.Size(); ++i)
			{
				TipBallState& State = TipContacts[s][Bodies[i].Ball];
				bool Present = false;
				for (int c = Cursor; c < ContactCount && !Present; ++c)
				{
					Present = Contacts[c].Tip == s && Contacts[c].A == i;
				}
				if (Present)
				{
					continue;
				}
				if (State.Active)
				{
					IslandContactRecord Record;
					Record.Kind = IslandRecordKind::TipEnd;
					Record.Time = StepTime;
					Record.BallA = Bodies[i].Ball;
					Record.Strike = s;
					NewRecords.PushBack(Record);
				}
				State = TipBallState{};
			}
		}

		ZeroForceSteps = AnyActive ? 0 : ZeroForceSteps + 1;
		CurrentTime = StepTime + Dt;
	}

	bool CompliantIsland::SustainedContact() const
	{
		if (CurrentMode != CliMode::Compliant)
		{
			return false;
		}
		bool AnyActive = false;
		for (const PairState& P : Pairs)
		{
			if (P.Active)
			{
				AnyActive = true;
				if (P.SlowSteps < Settings.SustainedSteps)
				{
					return false;
				}
			}
		}
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			for (const IslandBody& Body : Bodies)
			{
				const TipBallState& State = TipContacts[s][Body.Ball];
				if (State.Active)
				{
					AnyActive = true;
					if (State.SlowSteps < Settings.SustainedSteps)
					{
						return false;
					}
				}
			}
		}
		return AnyActive;
	}

	bool CompliantIsland::CanExit() const
	{
		if (ZeroForceSteps < Settings.ExitZeroForceSteps)
		{
			return false;
		}
		const double Touch = Tolerances.ContactTol;
		const double SpeedTol = Tolerances.ApproachSpeedTol;
		const double Leave = Tolerances.LeaveDistance;
		Vec3 Accel[kMaxBalls];
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			Accel[i] = FreeAcceleration(Bodies[i], Settings.ClothSupport && Bodies[i].ClothSupport, ClothSettings, GravityAccel, InPlaneGravityAccel,
				Tolerances);
		}

		// Gap >= 0 (touching band), separating (gap rate >= -v_eps) within LeaveDistance, and no pressing re-trigger
		// (touching, |rate| <= v_eps, gap'' < 0).
		auto CheckBallBall = [&](int I, int J)
		{
			const IslandBody& A = Bodies[I];
			const IslandBody& B = Bodies[J];
			const Vec3 D = B.Position - A.Position;
			const double Dist = Length(D);
			if (!(Dist > 0.0))
			{
				return false;
			}
			const double Gap = Dist - (A.Radius + B.Radius);
			if (Gap < -Touch)
			{
				return false;
			}
			if (Gap > Leave)
			{
				return true;
			}
			const Vec3 N = D / Dist;
			const Vec3 Dv = B.Velocity - A.Velocity;
			const double Rate = Dot(Dv, N);
			if (Rate < -SpeedTol)
			{
				return false;
			}
			if (Gap <= Touch && Abs(Rate) <= SpeedTol)
			{
				const double Second = (LengthSquared(Dv) - Rate * Rate) / Dist + Dot(Accel[J] - Accel[I], N);
				if (Second < 0.0)
				{
					return false;
				}
			}
			return true;
		};
		auto CheckFeature = [&](int I, int F)
		{
			const IslandBody& A = Bodies[I];
			FeatureHit Hit;
			if (!FeatureContact(Features[F], A.Position, A.Radius, Hit))
			{
				return true;
			}
			if (Hit.Gap < -Touch)
			{
				return false;
			}
			if (Hit.Gap > Leave)
			{
				return true;
			}
			const double Rate = Dot(A.Velocity, Hit.Normal);
			if (Rate < -SpeedTol)
			{
				return false;
			}
			if (Hit.Gap <= Touch && Abs(Rate) <= SpeedTol)
			{
				double Second = Dot(Accel[I], Hit.Normal);
				if (Hit.Curve && Hit.Distance > 0.0)
				{
					const Vec3 Across = A.Velocity - Hit.Normal * Rate - Hit.Tangent * Dot(A.Velocity, Hit.Tangent);
					Second += LengthSquared(Across) / Hit.Distance;
				}
				if (Second < 0.0)
				{
					return false;
				}
			}
			return true;
		};

		if (!PairsDirty)
		{
			for (const PairState& P : Pairs)
			{
				if (!(P.B >= 0 ? CheckBallBall(P.A, P.B) : CheckFeature(P.A, P.Feature)))
				{
					return false;
				}
			}
		}
		else
		{
			for (int i = 0; i < Bodies.Size(); ++i)
			{
				for (int j = i + 1; j < Bodies.Size(); ++j)
				{
					if (!CheckBallBall(i, j))
					{
						return false;
					}
				}
				for (int f = 0; f < Features.Size(); ++f)
				{
					if (!CheckFeature(i, f))
					{
						return false;
					}
				}
			}
		}
		for (int s = 0; s < kMaxStrikes; ++s)
		{
			if (!TipActive[s])
			{
				continue;
			}
			const Vec3 TipVelocity = Tips[s].Path.Direction * TipSpeed[s];
			for (const IslandBody& Body : Bodies)
			{
				const Vec3 D = Body.Position - TipCenter[s];
				const double Dist = Length(D);
				const double Gap = Dist - (Tips[s].Path.DomeRadius + Body.Radius);
				if (Gap < -Touch)
				{
					return false;
				}
				if (Gap <= Leave && Dist > 0.0 && Dot(Body.Velocity - TipVelocity, D / Dist) < -SpeedTol)
				{
					return false;
				}
			}
		}
		return true;
	}

	bool CompliantIsland::BodyAtRest(int Index) const
	{
		if (Index < 0 || Index >= Bodies.Size())
		{
			return false;
		}
		const IslandBody& Body = Bodies[Index];
		const double SpinLimit = Tolerances.EpsWTimesRadius / Body.Radius;
		return LengthSquared(Body.Velocity) <= Tolerances.EpsV * Tolerances.EpsV && LengthSquared(Body.Omega) <= SpinLimit * SpinLimit;
	}

	double CompliantIsland::GapToIsland(const Vec3& Position, double Radius) const
	{
		double Gap = kInfinity;
		for (const IslandBody& Body : Bodies)
		{
			Gap = Min(Gap, Length(Position - Body.Position) - (Radius + Body.Radius));
		}
		return Gap;
	}

	int CompliantIsland::FindBody(int Ball) const
	{
		for (int i = 0; i < Bodies.Size(); ++i)
		{
			if (Bodies[i].Ball == Ball)
			{
				return i;
			}
		}
		return -1;
	}
}
